### ISSUE TITLE
デザインシステム - shadcn/ui + Tailwind CSSセットアップ

### ISSUE THREAD

**Issue by s-hiraoku** [s-hiraoku/claude-core-reviewer#10]
## 概要
一貫したデザインシステムを構築し、shadcn/ui + Tailwind CSSによる統一されたUIコンポーネント群を実装します。アクセシビリティとレスポンシブデザインを重視します。

### 1. デザインシステム基盤
- [ ] カラーパレット定義
- [ ] タイポグラフィスケール
- [ ] スペーシングシステム
- [ ] ダーク/ライトテーマ対応
- [ ] CSS カスタムプロパティ設定

### 2. shadcn/ui セットアップ
- [ ] shadcn/ui CLI インストール・設定
- [ ] 基本コンポーネントインポート
- [ ] テーマ設定（`components.json`）
- [ ] カスタムスタイリング
- [ ] コンポーネントカタログ

### 3. 基本UIコンポーネント
- [ ] `Button` - プライマリ・セカンダリ・Ghost
- [ ] `Input` - テキスト・検索・URL
- [ ] `Card` - 基本カード・ヘッダー付き
- [ ] `Badge` - ステータス・重要度表示
- [ ] `Avatar` - ユーザーアバター

### 4. フォーム関連
- [ ] `Form` - フォーム管理
- [ ] `Label` - アクセシブルなラベル
- [ ] `Textarea` - 複数行テキスト
- [ ] `Select` - セレクトボックス
- [ ] `Checkbox` - チェックボックス
- [ ] `RadioGroup` - ラジオボタン

### 5. レイアウト関連
- [ ] `Header` - アプリケーションヘッダー
- [ ] `Sidebar` - ナビゲーションサイドバー
- [ ] `Container` - コンテンツコンテナ
- [ ] `Grid` - レスポンシブグリッド
- [ ] `Stack` - 垂直・水平スタック

### 6. フィードバック関連
- [ ] `Toast` - 通知メッセージ
- [ ] `Dialog` - モーダルダイアログ
- [ ] `AlertDialog` - 確認ダイアログ
- [ ] `Spinner` - ローディング表示
- [ ] `Progress` - プログレスバー

### 7. ナビゲーション関連
- [ ] `Tabs` - タブナビゲーション
- [ ] `Breadcrumb` - パンくずリスト
- [ ] `Pagination` - ページネーション
- [ ] `DropdownMenu` - ドロップダウンメニュー

### 8. 専用コンポーネント
- [ ] `StatusBadge` - レビューステータス
- [ ] `SeverityBadge` - 問題重要度
- [ ] `FileIcon` - ファイルタイプアイコン
- [ ] `CodeBlock` - コード表示
- [ ] `DiffStats` - 差分統計

### カラーパレット
```css
:root {
  /* ブランドカラー */
  --primary: 214 100% 50%;      /* #0080ff */
  --primary-foreground: 0 0% 98%;
  
  /* セマンティックカラー */
  --success: 142 76% 36%;       /* #16a34a */
  --warning: 38 92% 50%;        /* #f59e0b */
  --error: 0 84% 60%;           /* #ef4444 */
  --info: 200 98% 39%;          /* #0ea5e9 */
  
  /* ニュートラル */
  --background: 0 0% 100%;
  --foreground: 222.2 84% 4.9%;
  --muted: 210 40% 98%;
  --muted-foreground: 215.4 16.3% 46.9%;
  --border: 214.3 31.8% 91.4%;
  
  /* コードレビュー固有 */
  --code-addition: 142 76% 95%;
  --code-deletion: 0 84% 95%;
  --code-modification: 38 92% 95%;
  --comment-critical: 0 84% 95%;
}

[data-theme="dark"] {
  --background: 222.2 84% 4.9%;
  --foreground: 210 40% 98%;
  --muted: 217.2 32.6% 17.5%;
  /* ... */
}
```

### タイポグラフィ
```css
:root {
  --font-sans: 'Inter', system-ui, sans-serif;
  --font-mono: 'Fira Code', 'Monaco', monospace;
}

.text-xs { font-size: 0.75rem; }
.text-sm { font-size: 0.875rem; }
.text-base { font-size: 1rem; }
.text-lg { font-size: 1.125rem; }
.text-xl { font-size: 1.25rem; }
```

### スペーシング
```css
.space-1 { margin: 0.25rem; }
.space-2 { margin: 0.5rem; }
.space-4 { margin: 1rem; }
.space-6 { margin: 1.5rem; }
.space-8 { margin: 2rem; }
```

### StatusBadge
```tsx
interface StatusBadgeProps {
  status: 'pending' | 'analyzing' | 'completed' | 'failed'
  size?: 'sm' | 'md' | 'lg'
}

export function StatusBadge({ status, size = 'md' }: StatusBadgeProps) {
  return (
    <Badge 
      variant={getStatusVariant(status)}
      className={cn(
        'font-medium',
        size === 'sm' && 'text-xs px-2 py-0.5',
        size === 'md' && 'text-sm px-2.5 py-1',
        size === 'lg' && 'text-base px-3 py-1.5'
      )}
    >
      {getStatusLabel(status)}
    </Badge>
  )
}
```

### SeverityBadge
```tsx
interface SeverityBadgeProps {
  severity: 'critical' | 'major' | 'minor' | 'info'
}

export function SeverityBadge({ severity }: SeverityBadgeProps) {
  const variants = {
    critical: 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300',
    major: 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-300',
    minor: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300',
    info: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300'
  }
  
  return (
    <span className={cn('px-2 py-1 rounded-full text-xs font-medium', variants[severity])}>
      {severity.toUpperCase()}
    </span>
  )
}
```

## アクセシビリティ要件
- WCAG 2.1 AA準拠
- キーボードナビゲーション
- スクリーンリーダー対応
- 適切なカラーコントラスト（4.5:1以上）
- フォーカス管理

## レスポンシブ要件
- モバイル: 320px-767px
- タブレット: 768px-1023px
- デスクトップ: 1024px以上
- 最大幅: 1440px

## 受け入れ条件
- [ ] 一貫したデザインシステムが構築される
- [ ] 全コンポーネントがダーク/ライトテーマ対応
- [ ] レスポンシブデザインが正しく動作する
- [ ] アクセシビリティ基準を満たしている
- [ ] コンポーネントが再利用可能
- [ ] ストーリーブックでカタログ化
- [ ] パフォーマンスが良好

## 推定工数
2-3日

## 優先度
Medium - UI基盤

## 関連issue
- 関連: すべてのPhase（UIコンポーネントを使用）

## 注意事項
- ブランドアイデンティティの一貫性
- パフォーマンスへの影響最小化
- Tailwind CSS の最適化
- デザイントークンの管理

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>
